name: package
on: push
jobs:
    CI:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v3
          with:
            fetch-depth: "1"
        - name: Install Python and PIP
          run: sudo apt-get install pip python3-venv --no-install-recommends -yq
        - name: Install build
          run: pip3 install build
        - name: Build package
          run: python3 -m build
        - uses: actions/upload-artifact@v3
          with:
            path: ${{ github.workspace }}/dist/*.whl
        - uses: dev-drprasad/delete-older-releases@v0.2.0
          with:
            keep_latest: 3
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - uses: "marvinpinto/action-automatic-releases@latest"
          with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            automatic_release_tag: "latest"
            prerelease: true
            title: "Development Build"
            files: |
               ${{ github.workspace }}/dist/*.whl